#! /bin/sh

# -- Determine the overlay mountpoints from /proc/cmdline.

for o in $(cat /proc/cmdline); do

	case $o in

		znx_overlays=*)

			ZNX_OVERLAYS=${o#znx_overlays=}
			ZNX_OVERLAYS=$(printf $ZNX_OVERLAYS | sed 's/,/ /g')

		;;

	esac

done


# -- Find the persistent storage directory.

IMAGE_PERSISTENT_DATA=$(grep /cdrom /proc/mounts | cut -d ' ' -f 1)
IMAGE_PERSISTENT_DATA=${IMAGE_PERSISTENT_DATA%/*}


# -- Mount the requested overlays.

for k in $ZNX_OVERLAYS; do

	mkdir -p /root/isodevice/.overlay-tmp/$k.w

	[ -d /root/$k ] ||
		mkdir -p /root/$k

	mount -t overlay \
		-o lowerdir=/root/$k \
		-o upperdir=/root/isodevice/$IMAGE_PERSISTENT_DATA/$k \
		-o workdir=/root/isodevice/.overlay-tmp/$k.w \
		. /root/$k

done
